### ISSUE TITLE
Relic density section questions

### ISSUE THREAD

**Issue by caterina-doglioni** [LHC-DMWG/DMWG-2HDM-whitepaper#11]
Dear @AndreasAlbert,

I'm going through the relic section and I have a few clarifications for the readability of the text. 

1) We have the following sentence:

"For values of \ma beyond the LHC reach of a few TeV, the allowed parameter region at the top threshold $\mDM\approx m_{\mathrm{top}}$ remains independent of the value of \ma, indicating that a DM candidate that is mass degenerate with the top quark cannot be excluded by LHC searches alone."

This is not clear to me from the figure as it's off-scale. I would prefer to remove this statement, as I am not sure how relevant this is (ie why should the DM mass be the same as the top quark when we have this huge parameter space?) 

2) I would need a clarification on this sentence too:

"The cosmological production of DM is largely driven by the choice of $\mDM$, to which the collider searches are largely insensitive as long as the chosen value is small enough to allow DM production. Therefore, $\mDM$ may be freely tuned to yield the desired value of the relic density without spoiling the experimental constraint. "

In the kinematics section, we show that the DM value changes the MET distribution quite a bit as soon as mDM>Ma/2. However choosing points higher in mass won't help with the sensitivity, as the cross-section will lower the sensitivity, and that is the point I read between the lines. I've now rewritten the sentence as: 

The cosmological production of DM is largely driven by the choice of $\mDM$. As shown in \autoref{subsub:mDMKinematics}, the model kinematics is largely insensitive to this choice if $\mDM < 2 \ma$. Future experimental results that are sensitive to DM masses around 100 GeV which can yield the measured relic density can still be interpreted by rescaling samples generated according to this parameter scan. 

What do you think?

You can also have a look at the current version of the whitepaper in pdf in git, where the text of the first draft of the pseudoscalar experimental and relic sections are ready (we're only missing the harmonization of the cuts between monoH and monoZ and a clarification on the monoV(had) sensitivity). 

Thanks,
Caterina

**Comment by AndreasAlbert** [comment]
Hi @urania277, thank you for your careful reading! Regarding your questions:

1. The sentence refers to what  you can see in the right panel of Fig. 38, which has an extended axis range compared to the left panel. Note the horizontal cyan line at the low end of the y-axis. While I agree that there is no a-priori reason the DM should have a mass similar to the top, I find it interesting that you get a "hideout" for the DM at this mass value that is independent of the mediator mass. To me, one main question of the relic plots is always: "How much of the \Omegah^2 ~ 0.12 region can we exclude at the LHC?" Therefore, the fact that there is this hideout seems relevant to me. To make this more clear, one could change "...that is mass degenerate..." to "...that is **coincidentally** mass degenerate" or somethign similar.

2. I think we are in agreement about the physics statement: By "as long as the chocen value is small enough to allow DM production", I meant DM production with an onshell mediator, i.e. mDM < Ma/2. For mDM >= Ma/2, all bets are off. It's of course good to spell it out to avoid confusion. I find your rewrite of the sentence a little less clear than my original version, but that may be due to personal bias, so it's also fine to keep it as you propose.

Thanks

Andreas
