### ISSUE TITLE
Merging of material in "kinematics" section

### ISSUE THREAD

**Issue by caterina-doglioni** [LHC-DMWG/DMWG-2HDM-whitepaper#4]
Dear all,

first of all, thanks for providing high quality inputs! I have started trimming and editing the text in the DMWG_edited branch, and one thing that came to mind was that I would like to streamline section 4 into the following parts:

- kinematic distributions of the variables one wants to scan -> nearly complete for monoH/Z
- analyses that can be rescaled and procedure
- sensitivity of existing analysis
- reinterpretation/new signatures

Since this involved moving a number of files and figures around, could the monoH/Z analysers have a quick look and let me know if you agree with this idea /  if I have introduced any issues? It can be found in this file:

https://github.com/LHC-DMWG/DMWG-2HDM-whitepaper/blob/DMWG_edited/texinputs/04_grid/ModelKinematics.tex 

Thanks,
Caterina

**Comment by AndreasAlbert** [comment]
This state of the repository does not seem to compile out-of-the-box. 
This seems to be due to the file `texinputs/04_grid/figures/monoz/leptonic/mDMScan_ma250.pdf` being imported in the tex file but not present in the repo.
There seems to be a very similarly named `mDMscan...` (note lower case s), though. @cranelli Could you check?

**Comment by AndreasAlbert** [comment]
Hi @urania277,

If I understand correctly, you have changed the organization of the document from being sorted by final state/analysis to being ordered by aspect of study (e.g. kinematics, sensitivity.). This has two effects:

* In order to still be digestible, space needs to be saved. Thus, a bunch of information (i.e. kinematics, cross-section and acceptance plots) was moved to the appendix. Since these plots really inform everything else that is going on (e.g. significance calculations), I wonder if it is wise to remove them.
* Since multiple final states are talked about in the same section, the positioning of plots does not tell the reader what final state it is about. It is quite confusing to look at this very plot-rich document  and have to wonder what each plot is about. 

So, in total, I am not sure whether I would have chosen your approach of organizing the document. If we want to follow it, we should try to lessen the impact of the points above.

Best

A

**Comment by caterina-doglioni** [comment]
Hi @AndreasAlbert,

thanks a lot for reading the document and for your opinions! I agree with you that this is only a first draft so we can all contribute to improving it (or we can also go back to the previous approach).

The reason why I took the approach of going by aspect of study is that we are trying to tell a story to the reader on how we arrived to the parameter scan, rather than present a stand-alone truth-level analysis for each final state. So having the kinematics section first in this experimental part informs the reader on which parameters are scanned and what the impact of scanning is, then there is the central section of the recommendation of which grid points we have chosen, and then there is the final section where we show the sensitivity studies according to the grid. In this section we will mention that the grid has also been chosen so that Run-2 analyses would be able to discover a signal from this model, and forward-reference the sensitivity studies. 

Another reason why this approach was chosen is also because the studies are not completely homogeneous across final states, so being able to put examples rather than the whole set of plots mitigates these asymmetries without having to do more work (which is necessary as we want to finalize this paper on a reasonable timescale). 

About the cross-sections and acceptances: they are currently in the appendix, but they can be brought back to the sensitivity section which has not been edited yet. I still have to think how to structure that section, and I agree with you it probably makes sense to have them there. 

I also agree the positioning of plots needs fine-tuning - but I would prefer to do that as a last step, so that the text and the figures that the text refers to are near each other. 

Let me know what you think - and by all means, add whatever you think makes the section more readable. I won't work on this today, and tomorrow I will concentrate on the HF section which I can do on a separate file.

Caterina

PS the file with the wrong capitalization is something that no one with a non-case-sensitive mac noticed and it's fixed now - thanks!

**Comment by lhenkelm** [comment]
Hi @urania277 and @AndreasAlbert,

personally, I don't think there is a problem with sorting by aspect of study first. 
However, skimming over the kinematics section as it is now, I noticed a number of mix-ups regarding A and H, mA and mH, and their respective roles for the monon-h/mono-Z signal. E.g. in line 81:
"The pseudoscalar $A$ can be produced resonantly and decay in the $2\to1\to2$ process $gg\to A\to a h$ or $gg\to A\to a Z$, with the light pseudoscalar decaying invisibly as $a\to \chi\chi$. "
This is OK as far as mono-h is concerned, but  IIRC for mono-Z the relevant mediator would be H, not A.
In the same way mH, not mA, has the big effect on mono-Z kinematics.

To this, I have two questions:
1.  would it make sense to not do 
        section 1 :  ma,mA 
        section 2 : mH  
   which makes sense from the mono-h perspective, not so much for mono-Z,
    but rather have one section on ma,mA and mH? 
    In this section we would point out that
        - mA, ma determine the Jacobian peak for mono-h, mH changes resonant/non-resonant yield
        - mH, ma determine the Jacobian peak for  mono-Z, mA has little effect on the signal (do we have the plot for mono-Z mH= mHc fixed, mA varied?)
        - the effect of ma on the resonant signal, and that it  is very similar between mono-Z and mono-h
        - the choice mH = mA gives mostly resonant, thus varied, mono-h, and with similar kinematics to    mono-Z

2. should we at this point also check in detail for where these mix-ups occurred in the text, or should we rather wait until a later stage of editing/xchecks? 

Cheers,
Lars

**Comment by caterina-doglioni** [comment]
Hi @lhenkelm,

you're absolutely right that things are not matched correctly from that perspective, and it's a better idea to group things like you suggest. 

I am very happy if you and @AndreasAlbert take over that section and have a pass yourself, as it will be a good way to incorporate your feedback efficiently - you can still go back to the master branch for the previous text if you want to re-include something I omitted. This way I can concentrate on a first pass of the other sections and then when I am looking at the sensitivity we proceed in the same way. Would that work for you? 

Thanks,
Caterina

**Comment by AndreasAlbert** [comment]
@lhenkelm I think your proposal is good (and necessary). We did not produce any plots scanning mA alone for Mono-Z, so in principle mA = mH everywhere on the mono-Z plots.

**Comment by lhenkelm** [comment]
Hi @urania277, @AndreasAlbert 
then we agree. Today I am busy, but I'll try to get some rearrangements/edits done tomorrow or Thursday. 
Cheers, 
Lars

**Comment by caterina-doglioni** [comment]
Hi @lhenkelm, @AndreasAlbert, @obrandt1, @cranelli, @syuvivida‚  @polesell, @priscillapani, @fungaro, 

I've done some more smoothing work on the two sections kinematics (including ttbar rescaling) and choice of grid so that they are more or less self-consistent. I would like your input (and edits, if you'd like) on it. The idea is that these two sections can stand on their own after the theory section to justify our choice of parameters to vary on the grounds that varying them gives interesting kinematics. 

Note that the DM mass is a different story as we keep it low so that we are sensitive but then vary it to get closer to a region where the model is compatible with relic density. 

Let me know what you think preferably by the end of the coming week, and you're welcome to keep discussing here. I will move on with the sections on sensitivity and other searches that are sensitive to the mode, and post those when I have made some progress. 

Thanks,
Caterina

**Comment by caterina-doglioni** [comment]
The PDF corresponding to what is in the tex is here: 
https://github.com/LHC-DMWG/DMWG-2HDM-whitepaper/blob/DMWG_edited/DMWG-2HDM-whitepaper_Main_KinematicsGrid.pdf

**Comment by obrandt1** [comment]
Hi @urania277 
Could you please clarify which sections you are referring to by "two section kinematics"? (sorry if I'm missing something obvious)

**Comment by caterina-doglioni** [comment]
Hi @obrandt1, 
sorry I wasn't clear - those are the two chapters in the pdf above, found in the tex files:
texinputs/04_grid/ModelKinematics.tex
texinputs/04_grid/RescalingDMHF.tex
texinputs/04_grid/ParameterGrid.tex
Note that the new versions are in the dmwg_edited branch, the master branch is there for reference as that is where everyone committed to before the edits. 
Thanks!
Caterina

**Comment by cranelli** [comment]
Hi Caterina,
Thank you for organizing the Kinematic studies of all the analyses.
For Figures 17 and 19, I just pushed new Mono-Z(ll) plots that have labels added.  In particular, for Figure 17, I switched to a mass point at mH=600 ma=200, so the results are directly comparable with Mono-H.
Cheers

**Comment by lhenkelm** [comment]
Hi @urania277, all,
I went through the kinematics section up to sin(theta), with a few small edits mostly to clear up monoH/monoZ and the roles of mA/mH wherever they got mixed in the rearranging. 

I noticed a paragraph in the sin(theta)  section giving a detailed description of Figure 17 (a), making it sound like the particular dependence on sin(theta) for ma=200 GeV, mA = 600 GeV was universal (not sure if that was by intent, or who wrote it).
This pragraph is commented out for now. The sin(theta) dependence for mono-h is different at different mass points,
so the statement, as universally as it was written, was not true. I would either just not discuss this, or put a second plot e.g. at 350, 1000 to give an example of these differences, and discuss it with the help of the plot. Since it's these differences that motivate the two sin(theta) scans, that may be worth considering.

Cheers,
Lars
