### ISSUE TITLE
Mono-H sensitivity: clarification on sentence

### ISSUE THREAD

**Issue by caterina-doglioni** [LHC-DMWG/DMWG-2HDM-whitepaper#8]
Hi @lhenkelm and @obrandt1, 

I came across the following sentence that confuses me slightly: 

> The sensitivity above the mass diagonal, $\mA > \ma$, is larger than below the mass diagonal.
> Two parameter choices cause this asymmetry:
> \begin{enumerate}
> \item 
> The choice of $\mA = \mH = \mHc$ forces the neutral and charged $CP$-even scalars to have lower masses below the diagonal and higher masses above the diagonal. 
> As it can be seen in \autoref{fig:monoHbb_mH_scan_met}, when $\mH = \mHc$ are below the mass of the higher-mass pseudoscalar $A$, there is a lower fraction of resonant signal events, and a reduced total cross-section. 
> 

This sentence says that \mA = \mH = \mHc, but the plot we use shows that we vary mH and fix mA. 

Could you please help me clarify?

Thanks,
Caterina

**Comment by lhenkelm** [comment]
Hi @urania277,

which plot are you referring to? I am not sure what you would like to clarify.
In the mass-mass scan (which we, following the monoH usage, usually refer to as ma-mA scan), we vary ma in x, and mA,mH,mHc simultaneously in y , such that mA = mH = mHc. The choice of mA = mH = mHc is kept in all scans, i.e. ma-mA in Figure 28, ma-tanbeta in Figure 29, both sintheta scans in Figure 30, and the mDM scan in Figure 31.

This is also what is done in Figure 6 [here](https://github.com/LHC-DMWG/DMWG-2HDM-whitepaper/blob/DMWG_edited/DMWG-2HDM-whitepaper_Main.pdf).
In Figure 13 we fix mA and vary only mH = mHc, to illustrate the reasoning behind that choice, but it is not part of any of the proposed benchmarks. The situation below the diagonal is in a sense similar to what Figure 13 shows, because ma (now > mA, i.e. the mass of the heavy pseudoscalar), is not = mH = mHc. Instead the lighter pseudoscalar A is mass degenerate. 

Would this be clearer if we explicitly reference that there is the a-priori symmetry ma <--> mA, sin(theta) <--> cos(theta) of the model?

Cheers,
Lars

**Comment by caterina-doglioni** [comment]
Hi @lhenkelm, 

thanks for the quick response and sorry for omitting the reference to the plot. I was indeed referring to figure 13. What you say about the symmetry of the model will help clarify things: I think the text as I edited it in is confusing as it says that mA is the heavier pseudoscalar. 

I've rewritten as:

The choice of $\mA = \mH = \mHc$ forces the neutral and charged $CP$-even scalars to have lower masses below the diagonal and higher masses above the diagonal, leading to configurations with a lower fraction of resonant signal events. One can use \autoref{fig:monoHbb_mH_scan_met} to exemplify this behaviour. Considering the symmetry between the two pseudoscalars, when the neutral and charged scalars $\mH = \mHc$ are lighter than one of the two pseudoscalars (marked as $A$ in the figure, but effectively representing $a$ in the case of this scan because of the symmetry), one can see that non-resonant configurations are preferred. This also yields a reduced total cross-section. 

Do you think this works?
Thanks,
Caterina
